from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    OWNER = "OWNER"
    LABELER = "LABELER"
    REVIEWER = "REVIEWER"
    SYSTEM = "SYSTEM"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    PAUSED = "PAUSED"
    ENDED = "ENDED"


class DistributionStrategy(StrEnum):
    FIRST_COME_FIRST_SERVED = "FIRST_COME_FIRST_SERVED"
    ASSIGNED = "ASSIGNED"
    QUOTA_GRAB = "QUOTA_GRAB"


class DatasetType(StrEnum):
    QA_QUALITY = "QA_QUALITY"
    PREFERENCE_COMPARE = "PREFERENCE_COMPARE"
    CUSTOM = "CUSTOM"


class DatasetSourceFormat(StrEnum):
    JSON = "JSON"
    JSONL = "JSONL"
    EXCEL = "EXCEL"
    MIXED = "MIXED"


class DatasetStatus(StrEnum):
    IMPORTING = "IMPORTING"
    READY = "READY"
    FAILED = "FAILED"


class DatasetItemStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    CLAIMED = "CLAIMED"
    DISABLED = "DISABLED"


class AssignmentStatus(StrEnum):
    CLAIMED = "CLAIMED"
    DRAFT_SAVED = "DRAFT_SAVED"
    SUBMITTED = "SUBMITTED"
    RETURNED = "RETURNED"
    APPROVED = "APPROVED"
    CANCELLED = "CANCELLED"


class SubmissionStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    AI_REVIEWING = "AI_REVIEWING"
    HUMAN_REVIEWING = "HUMAN_REVIEWING"
    RETURNED = "RETURNED"
    APPROVED = "APPROVED"


class ReviewJobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class AiReviewConclusion(StrEnum):
    PASS = "PASS"
    RETURN = "RETURN"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class ReviewStatus(StrEnum):
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    APPROVED = "APPROVED"
    RETURNED = "RETURNED"


class HumanReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    RETURN = "RETURN"
    DIRECT_REVISE = "DIRECT_REVISE"


class ContributionBucket(StrEnum):
    ALL = "ALL"
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    RETURNED = "RETURNED"
    REVISION_REQUIRED = "REVISION_REQUIRED"


class LlmActionRunStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ImportStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ReviewConfigVersionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class TemplateComponentType(StrEnum):
    SHOW_ITEM = "SHOW_ITEM"
    TEXT_INPUT = "TEXT_INPUT"
    TEXTAREA = "TEXTAREA"
    RADIO = "RADIO"
    CHECKBOX = "CHECKBOX"
    TAG_SELECT = "TAG_SELECT"
    RICH_TEXT = "RICH_TEXT"
    FILE_UPLOAD = "FILE_UPLOAD"
    IMAGE_UPLOAD = "IMAGE_UPLOAD"
    JSON_EDITOR = "JSON_EDITOR"
    LLM_ACTION = "LLM_ACTION"
    GROUP = "GROUP"
    TABS = "TABS"


class TemplateVersionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class PublishBlockerCode(StrEnum):
    INVALID_TASK_STATUS = "INVALID_TASK_STATUS"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    MISSING_DATASET = "MISSING_DATASET"
    MISSING_TEMPLATE_VERSION = "MISSING_TEMPLATE_VERSION"
    MISSING_REVIEW_CONFIG = "MISSING_REVIEW_CONFIG"
    INVALID_QUOTA = "INVALID_QUOTA"
    INVALID_DEADLINE = "INVALID_DEADLINE"


class FilePurpose(StrEnum):
    IMPORT = "IMPORT"
    EVIDENCE = "EVIDENCE"
    EXPORT = "EXPORT"


class AuditEntityType(StrEnum):
    TASK = "TASK"
    DATASET = "DATASET"
    DATASET_ITEM = "DATASET_ITEM"
    IMPORT_JOB = "IMPORT_JOB"
    REVIEW_CONFIG = "REVIEW_CONFIG"
    TEMPLATE = "TEMPLATE"
    ASSIGNMENT = "ASSIGNMENT"
    SUBMISSION = "SUBMISSION"
    REVIEW_JOB = "REVIEW_JOB"
    REVIEW = "REVIEW"
    LLM_ACTION_RUN = "LLM_ACTION_RUN"
    FILE_OBJECT = "FILE_OBJECT"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    STATE_TRANSITION = "STATE_TRANSITION"
    IMPORT_CREATE = "IMPORT_CREATE"
    IMPORT_COMPLETE = "IMPORT_COMPLETE"
    BATCH_UPDATE = "BATCH_UPDATE"
    REVIEW_CONFIG_SAVE = "REVIEW_CONFIG_SAVE"
    REVIEW_CONFIG_PUBLISH = "REVIEW_CONFIG_PUBLISH"
    TEMPLATE_SAVE = "TEMPLATE_SAVE"
    TEMPLATE_PUBLISH = "TEMPLATE_PUBLISH"
    PUBLISH_CHECK = "PUBLISH_CHECK"
    ASSIGNMENT_CLAIM = "ASSIGNMENT_CLAIM"
    ASSIGNMENT_DRAFT_SAVE = "ASSIGNMENT_DRAFT_SAVE"
    SUBMISSION_CREATE = "SUBMISSION_CREATE"
    REVIEW_JOB_CREATE = "REVIEW_JOB_CREATE"
    REVIEW_JOB_CLAIM = "REVIEW_JOB_CLAIM"
    REVIEW_JOB_RESULT = "REVIEW_JOB_RESULT"
    REVIEW_AI_SUGGESTION = "REVIEW_AI_SUGGESTION"
    REVIEW_DECISION = "REVIEW_DECISION"
    LLM_ACTION_RUN = "LLM_ACTION_RUN"
